### ISSUE TITLE
make it compatible with kiwibrowser a chromium fork (5m user)

### ISSUE THREAD

**Issue by mycal123** [mrcoles/full-page-screen-capture-chrome-extension#100]
**Describe the bug**

**To Reproduce**

1. Go to URL '...'
4. Got error '....' / see screenshot / etc.

**Expected behavior**

**Screenshots**

**System (please complete the following information):**

 - OS: [e.g. Mac OS X 10.13.5, Windows 10.0.0, 18.04.1 LTS]
 - Browser and version [e.g. Chrome v68.0.3440]
 - Extension version [e.g. 4.8] (get from chrome://extensions/?id=fdpohaocaechififmbbbbbknoalclacl)

**Additional context**

**Comment by mrcoles** [comment]
@mycal123 this is an issue with Kiwi not supporting the `captureVisibleTab` API https://github.com/kiwibrowser/src/issues/304
