### ISSUE TITLE
Any way to adjust for PDF files loaded in Chrome?

### ISSUE THREAD

**Issue by ghost** [mrcoles/full-page-screen-capture-chrome-extension#102]
This is an amazing tool. There are times when I can't download a PDF, but want to capture the PDF in screenshot form.

**Comment by mrcoles** [comment]
Hi @lcs207 , if you’re hoping to scroll and capture a PDF that you’re viewing in the browser, they are rendered in a special way that leaves them unscrollable by the extension (or any JavaScript on the page). If it’s something else, you can reach out to the support feature in the extension for support on the current web store version of the extension (the flag icon at the top of the page after taking a screenshot). This is the original open-source repo for the project, which I’ve left available for posterity and as a resource for others!
