### ISSUE TITLE
Question on Full Page extension

### ISSUE THREAD

**Issue by aina-kamarul-chan** [mrcoles/full-page-screen-capture-chrome-extension#116]
Hello, based on the image below, I notice the extension records the url of the images. Does the images and url extension are stored locally on my machine and not to the server which I assume that is not the case. 

<img width="821" alt="image" src="https://github.com/mrcoles/full-page-screen-capture-chrome-extension/assets/114457471/7e7109bf-638e-4328-869a-2b067f828816">

I. notice that the permission below stated that it can access the url which I feel unsafe as I might want to screenshot sensitive information and the permission enable the system to know what url I have visited,
<img width="1151" alt="image" src="https://github.com/mrcoles/full-page-screen-capture-chrome-extension/assets/114457471/e0ee1b9a-26d0-478b-9d48-f84f1b45de54">

**Comment by aina-kamarul-chan** [comment]
Can you share what are the permissions that will be used for Full Page extension? Since you stated that you run a private repo to host the extension.

**Comment by catbrew** [comment]
The author probably added things to monetize the app aka now YOU'RE the product. Otherwise there would be no reason to suddenly take the code private. The one in the Chrome Webstore is NOT the one on GitHub. Plenty of options like PDF support could have been added with Open Source code that largely already exists.
If the author wants to make a buck, so be it, but don't also link to an Open Source GitHub extension that is missing the code from the one in the Chrome store. If I'm wrong and they're so similar, why isn't the new code public in GitHub? Doesn't take a genius to know trying to pretend this isn't an issue and continuing to advertise the closed source one together with the old GitHub code means there's something in the private code the author doesn't want the public to see. Could've just come clean about making a different extension that has code users wouldn't like if they knew about it.

**Comment by mrcoles** [comment]
@aina-kamarul-chan this repo is just here for historic purposes—I’m assuming you’re asking about the web store extension? Images are stored locally on your machine only. It uses the FileSystem API and IndexedDB to manage the screenshot data within Chrome. You can view your screenshots in the extension by going to the “Files” nav item after taking a screenshot. From there you can delete, view, and download them.

The <all_urls> permission gets requested when you screenshot a page that doesn’t scroll, but has iframes in it. Those pages cannot be accessed without asking for extra permissions. There’s a long discussion about it in this bug report that I filed: https://bugs.chromium.org/p/chromium/issues/detail?id=826433 Understandably, it’s more complex of a problem than it initially might seem.

The extension tries its best to communicate when it asks for permissions, e.g., in the case you’re referring to, this is what it shows:

<img width="327" alt="Screenshot 2024-01-31 at 7 43 43 PM" src="https://github.com/mrcoles/full-page-screen-capture-chrome-extension/assets/136651/4fc21a52-0ff8-417d-9c4b-0005c95f1e33">

If you go to settings (gear icon in the extension) and scroll to the bottom and click on permissions, then you’ll see the extra perms that are requested and an option to disable them:

<img width="992" alt="Screenshot 2024-01-31 at 7 38 35 PM" src="https://github.com/mrcoles/full-page-screen-capture-chrome-extension/assets/136651/9a21f3e5-0d49-4149-8282-947375320443">

Regardless, the extension is only able to run when you click on it, so it can’t access anything other than the page you’re capturing.

And to answer your initial question, if you take a look at the manifest of the webstore app, you’ll see (still on manifest v2):

```
    "permissions": [
        "activeTab",
        "storage",
        "unlimitedStorage"
    ],
    "optional_permissions": [
        "downloads",
        "<all_urls>",
        "webNavigation",
        "file://*/*"
    ],
```

---

@amamelia the webstore version has been on a forked repo for [almost 6 years now](https://github.com/mrcoles/full-page-screen-capture-chrome-extension/commit/350d415f76f435f48e5c5e5174927cc0d71e79c3) as seen on the README for the project. Also, I covered why I created a paid premium option in [this blog post](https://blog.gofullpage.com/2023/02/10/10-questions-with-gofullpage-founder-peter-coles/):

> I originally built this as a little side project to solve a specific problem and put it up as open source on [GitHub](https://github.com/mrcoles/full-page-screen-capture-chrome-extension). I figured it’d be helpful to other people too and was excited when I saw rising install numbers on the extension, and even more so, when I got some issues and PRs on the repo.
> 
> Over time, the number of users grew massively and the work to keep things running smoothly was increasing. The customer support integration is critical to the extension being as effective as it is, and managing that alone was becoming unmanageable. So I sought a way to fund the continued existence of the extension and was determined to do so in an ethical way. As a result, instead of advertising or data harvesting, I decided to launch a premium service that provided editing, annotating, and more to the screenshotting. The original capturing remains free, but this provides a way to offer more to power users and to those who want to support the extension.
