### ISSUE TITLE
Capture pages that have fixed position footers

### ISSUE THREAD

**Issue by mrcoles** [mrcoles/full-page-screen-capture-chrome-extension#21]
Currently the application has a buffer for capturing the top of the screen in order to try and not repeat fixed position content in the header. There is nothing to handle this issue with footers.

Example pages with this problem:
-   http://www.designboom.com/design/interview-with-graphic-designer-gareth-hague-06-23-2014/
-   https://www.grafik.net/category/talent/kathy-lam (some other issues that might be tough to stop on this one)

**Comment by kosiakk** [comment]
This is also a problem with Facebook chat (a floating bar).

I'd say, all elements with `style="position: fixed"` should be temporarily hidden during the save. Only the topmost screenshot should contain them.

**Comment by UziTech** [comment]
you could try changing `position: fixed` to `position: absolute`

**Comment by mrcoles** [comment]
Ya, lately I’ve just been telling people to just switch things to `position: absolute` using Chrome Developer Tools and then taking a screenshot afterwards :smile: but at some point I might make a change to better support this use-case.

**Comment by mrcoles** [comment]
The [webstore version](https://chrome.google.com/webstore/detail/full-page-screen-capture/fdpohaocaechififmbbbbbknoalclacl?hl=en-US) has a number of improvements to this. It’s a pretty finicky problem to solve though and will probably take a good deal of iteration to handle the varying use-cases out there.
