### ISSUE TITLE
height/width calculations fail on framesets

### ISSUE THREAD

**Issue by pjvandehaar** [mrcoles/full-page-screen-capture-chrome-extension#22]
Eg, http://www.quackit.com/html/templates/frames/frames_example_1.html.

`document.documentElement.scrollHeight`, etc are all `window.innerHeight`.

**Comment by mrcoles** [comment]
I’m leaving out frameset support for now. You can checkout some workarounds in #58

**Comment by pjvandehaar** [comment]
That seems like a good choice.  I still think it'd be good to let users know what's going on when the extension fails on a frameset (as per https://github.com/mrcoles/full-page-screen-capture-chrome-extension/issues/22#issuecomment-53315539), but you're free to do whatever you like.
