### ISSUE TITLE
Image is blank

### ISSUE THREAD

**Issue by samlstarkey** [mrcoles/full-page-screen-capture-chrome-extension#24]
I've run a couple of full page scrolling captures which worked fine, but a recent one just results in a blank image. Something I'm doing?
![image](https://cloud.githubusercontent.com/assets/7466560/4791030/a78ce65a-5dd8-11e4-85f8-a39c770fc91c.png)

Was capturing this page:https://twitter.com/GAIN_Torbay/followers using Chrome Version 37.0.2062.120 m

**Comment by mrcoles** [comment]
I’m guessing you scrolled for ages and made the page extremely long? This creates such a large image that Chrome silently fails on me. The upcoming release 1.0.0 will break up extremely large images into multiple if necessary.
