### ISSUE TITLE
Save images under different names

### ISSUE THREAD

**Issue by Marcoevich** [mrcoles/full-page-screen-capture-chrome-extension#25]
Hi sir! How are you?

Can you please add the ability to save screenshots from the same website under a different name? I like to compare screenshots of the same website, but you can only create one screenshot from each site. As soon as you create another, the first one can't be saved anymore even though it is opened in it's own tab.

**Comment by HetIsNiels** [comment]
It would be nice if the names would add the time stamp to the end of the name. I made some screenshots yesterday from a project I work on and today when I made new screenshots the old ones where overwritten.

**Comment by mrcoles** [comment]
Yeah, timestamp would be a simple solution. If you want to submit a pull request, it’d probably happen sooner than I can get to it :smile:

**Comment by tobi-or-not** [comment]
Looks like this feature has been implemented. It's not an issue any longer and could be closed
