### ISSUE TITLE
Any idea how to do screen recording similar way ?

### ISSUE THREAD

**Issue by bismoy2013** [mrcoles/full-page-screen-capture-chrome-extension#26]
Very nice screen capture app, but I was just wondering if you might know how to recording screen as well .

**Comment by mrcoles** [comment]
You’re asking about recording video? That’s definitely outside the scope of this extension.

You might want to look into desktop screen recording software. However, unless there’s some browser api for video capture that I’m aware of, you could at least try building an extension that takes screen shots of just the visible page on a regular interval and then pieces them together—wouldn’t be amazing, but depending on what you’re looking for it might work :smile:
