### ISSUE TITLE
Crashes Chrome when you try to capture a page while the icon is hidden

### ISSUE THREAD

**Issue by JannesMeyer** [mrcoles/full-page-screen-capture-chrome-extension#28]
Here are the steps to reproduce the crash:

1. Assign a keyboard shortcut for 'Activate the extension'
2. Hide the browser action by right-clicking it and selecting 'Hide Button'
3. Use the previously assigned keyboard shortcut

Expected behavior:
Don't show the popup, but still capture the page

**Comment by mrcoles** [comment]
Cool, thanks :+1:  I’ll take a look when I get a chance! I didn’t realize Chrome allowed you to assign a keyboard shortcut for “Activate the extension”—I also wonder if there’s a deeper bug in Chrome on this one?

**Comment by mrcoles** [comment]
Just tried this in `Version 50.0.2661.94 (64-bit)` on Mac OSX. Worked fine—maybe the fixed it on their side 😏 

Thank you for the report though! 🍻
