### ISSUE TITLE
Can not copy and paste image into Word

### ISSUE THREAD

**Issue by xiaozj** [mrcoles/full-page-screen-capture-chrome-extension#29]
Not sure why PNG image generated can not be directly copy and pasted into Microsoft Word - what gets pasted is a small blank square.

I have to either paste into MS Paint and then copy and paste from that into Word, or save the PNG first and go from there.

When I test a PNG file from a regular website, it doesn't have this problem, what gives?

**Comment by mrcoles** [comment]
This sounds quite peculiar, but other applications can do quirky things. Sorry for the late response, but did you also try just dragging it to your desktop, then to MS Word?
