### ISSUE TITLE
Failing for long page

### ISSUE THREAD

**Issue by stefrobb** [mrcoles/full-page-screen-capture-chrome-extension#34]
The extension fails for this page: http://urbanglasgow.co.uk/ftopic1654-0-asc-0.php

This is the first page of a forum thread, it's a long one, with *lots* of images.  The extension goes through the usual motions but when complete a blank tab is opened.   The URL of the tab is the usual extension temporary filename, but there's nothing on the actual canvas—so nothing to save.

It works just fine for page 2 of that thread, which is considerably shorter!

I'm assuming that this is something to do with the length of the page?

**Comment by chihaoyo** [comment]
Bumping into the same issue. Is it the case that Chrome is limiting the size of file that can be cached?

**Comment by mrcoles** [comment]
Yes, Chrome limits the size of the file that can be generated.

Upcoming release 1.0.0 will create multiple images if the page is too large (>99% of the web isn’t too large).
