### ISSUE TITLE
Compatibility Reports

### ISSUE THREAD

**Issue by pguth** [mrcoles/full-page-screen-capture-chrome-extension#36]
Since you mentioned in the README that you couldn't test, I thought I should (happily) report:

- [x] Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/43.0.2357.130 Safari/537.36 [Chromium actually]

**Comment by mrcoles** [comment]
Hey @pguth can you elaborate on what compatibility problem you’re seeing?

**Comment by pguth** [comment]
Ah, none! It works. That was the information I wanted to provide. You wrote in the [README](https://github.com/mrcoles/full-page-screen-capture-chrome-extension/blob/master/README.md):

> So, I built this one to reliably do it. (Not tested, yet, on any other configurations.)

And I thought we could collect compatibility data here.

**Comment by mrcoles** [comment]
Oh, thanks! :+1:
