### ISSUE TITLE
Screenshot breaks when taking mobile screenshots on desktop

### ISSUE THREAD

**Issue by eemccue** [mrcoles/full-page-screen-capture-chrome-extension#39]
When using Device mode to simulate mobile or tablet, the screenshots often have "breaks" between chunks of the page view.

![screencapture-www-etsy-com-search-1448479808434](https://cloud.githubusercontent.com/assets/1256572/11407507/4b669634-9381-11e5-958c-b2f742d43e84.png)

**Comment by mrcoles** [comment]
Fixed in upcoming release 1.0.0. Also, nice rugs!
