### ISSUE TITLE
Capturing Screens of Extensions

### ISSUE THREAD

**Issue by SunburnedGoose** [mrcoles/full-page-screen-capture-chrome-extension#40]
What's the limitation from the webstore to allow your extension to capture the screen of another extension?  I made an extension called Destiny Item Manager and users have been asking for a screen shot feature.  I tried yours and got the blocked message.  

Is it just a permission that has to be given to enable interaction with Chrome extensions?

**Comment by mrcoles** [comment]
If I don’t block it, then the following line:

```javascript
chrome.tabs.executeScript(tab.id, {file: 'page.js'}, function() {
    …
}
```

Gets this error:

> Unchecked runtime.lastError while running tabs.executeScript: The extensions gallery cannot be scripted.

I might be missing something in your request though. When folks are using your extension, is it on a URL starting with: `https://chrome.google.com/` ? If so, what specifically does it look like?

You could try cloning this repo, changing the following line in popup.js `noMatches = [/^https?:\/\/chrome.google.com\/.*$/]` to `noMatches = []`, going into extensions and loading it as an "unpacked extension", then trying to see what happens.

**Comment by tylerjharden** [comment]
Google Chrome Security Policy forbigs you from executing scripts on Google Chrome internal and Web Store pages. There is no possible workaround.

**Comment by mrcoles** [comment]
Yes, thank you @tylerjharden
