### ISSUE TITLE
Background.js instead of Popup.js?

### ISSUE THREAD

**Issue by jasondavis** [mrcoles/full-page-screen-capture-chrome-extension#43]
I am trying to use this code modified to use the `background.js` page instead of `popup.js` to handle running Chrome API and building the full screen Canvas image.

The reason is that my extension shows a Modal window on the website.  Because my app also allows user to select a region for a screenshot and than returns that image in the form of filling in a form filed and showing preview for a Bookmarking app.

If I was to use the `Popup.js` instead, it would close my Bookmark app when user chose to do a selection screenshot and then would be unable to re-open that window again to fill in the new data captured.

So I moved to a Modal window in a `content.js` file.

My problem now with trying to use this code in my content script and a Background.js file is that on 1st iteration Background should create the canvas.  On 2nd, 3rd, etc...the code errors as it cannot find the canvas!

Apparently Background handles this differently.

Any ideas how I might get this working?

**Comment by mrcoles** [comment]
I’m not sure. When I put this together year ago, I believe only popup could take screenshots, but maybe content can too? That is why it’s setup as it is to send relevant notes about the page from background to the popup, so it knows what it’s capturing.

With your issue for the background.js, sounds like a scope issue. Are you defining a reference to the variable in the top-level of the file? Or if that’s not possible with background.js, is there a way to pass around a reference between calls? Sorry, I wouldn’t know more without researching it.
