### ISSUE TITLE
Extension running on chrome canary 52

### ISSUE THREAD

**Issue by derekoakley** [mrcoles/full-page-screen-capture-chrome-extension#50]
For me since version 52.0.2726.0 of chrome canary (64-bit) the extension seems to work up to the point where a new tab opens to display the image but no image appears and tab is stuck with a spinner indicator. Any ideas?

**Comment by mrcoles** [comment]
@derekoakley what URL are you trying to capture? Is it by chance a huge page? What if you try this current one: https://github.com/mrcoles/full-page-screen-capture-chrome-extension/issues/50 ?

**Comment by derekoakley** [comment]
@mrcoles it's all pages unfortuantly regardless of size

**Comment by mrcoles** [comment]
Can you right-click on the popup window where the spinner is, click inspect, and take a look at the console to see what error you see (if any)?

Also, there are a bunch of general updates, fixes, and some deprecation updates in 1.0.0 (current master), but it’s “pending review” in the chrome web store. You could also try cloning this repo, loading it as an unpacked extension, and then running the same check as above.

**Comment by derekoakley** [comment]
With the version from the web store the console tab doesn't show any errors and the elements tab shows an empty page.

However that master version works a treat! Only downer is the spinner still endlessly shows on the tab that pops up.

**Comment by mrcoles** [comment]
OK, I wonder if there’s something in the newer Chrome that requires manually closing the popup. I assume you can close it by clicking on the extension icon again?

**Comment by derekoakley** [comment]
Sorry by pop up I mean the tab that pops up with the completed screen shot, usually titled 'screen-capture-...'

**Comment by mrcoles** [comment]
Oh, meaning that the image never loads? Or do you have a screenshot of it?

**Comment by derekoakley** [comment]
Sorry in hindsight I should have just screen recorded my issue!

This is the version from the web store:
![store mov](https://cloud.githubusercontent.com/assets/717353/15124932/48182f00-1622-11e6-9c88-aa132699948c.gif)

This is unpacked from master:
![master mov](https://cloud.githubusercontent.com/assets/717353/15125115/2028a078-1623-11e6-9b97-abbac5a4102f.gif)

**Comment by mrcoles** [comment]
great thanks!

**Comment by mrcoles** [comment]
Hopefully one of my releases has addressed this. Various changes have been updated in the chrome store, please try the latest and report through there if you’re still getting errors: https://chrome.google.com/webstore/detail/full-page-screen-capture/fdpohaocaechififmbbbbbknoalclacl?hl=en-US

Thanks! 😄
