### ISSUE TITLE
Repeats WordPress left sidebar 

### ISSUE THREAD

**Issue by paaljoachim** [mrcoles/full-page-screen-capture-chrome-extension#53]
Hey

I just installed your Chrome extension and like other extensions I have tried it repeats the left sidebar menu in WordPress.

![screencapture-test1-dev-wp-admin-themes-php-1466667494624](https://cloud.githubusercontent.com/assets/5323259/16295331/83df8b06-3926-11e6-86b9-286c16b73d53.png)

**Comment by mrcoles** [comment]
I’ll keep this in mind with upcoming scroll improvements, thanks.
