### ISSUE TITLE
extensions::uncaught_exception_handler:8 Error in event handler for (unknown): TypeError: 

### ISSUE THREAD

**Issue by strongant** [mrcoles/full-page-screen-capture-chrome-extension#55]
extensions::uncaught_exception_handler:8 Error in event handler for (unknown): TypeError: Cannot read property 'size' of undefined
    at chrome-extension://ldacmkkiekeppnjkkmffnkfklhkpmcih/scripts/api.js:291:27
    at chrome-extension://ldacmkkiekeppnjkkmffnkfklhkpmcih/scripts/api.js:268:11
    at chrome-extension://ldacmkkiekeppnjkkmffnkfklhkpmcih/scripts/api.js:41:7

**Comment by mrcoles** [comment]
Thank you for the stack trace. I will take a look!

Can you also share…

Chrome version:
Operating System:
Computer type:
URL for page being captured:

**Comment by mrcoles** [comment]
@strongant ping 🍍

**Comment by strongant** [comment]
I use your CaptureAPI Complete the screen capture,Encountered this problem.

**Comment by mrcoles** [comment]
@strongant can you also share…

Chrome version: ??
Operating System: ??
Computer type: ??
URL for page being captured: ??

**Comment by strongant** [comment]
Chrome version: 52.0.2743.116 m (64-bit)
Operating System: Ubuntu
Computer type: HASEE
URL for page being captured: http://www.taobao.com/

**Comment by mrcoles** [comment]
Great, thanks for the response. It’s not happening for me with the same chrome version and site on my MacBook running OS X. This happens for you with any URL you try? (I’ll have to try it out on Ubuntu when I get a chance!)

Also, I released v2.0 of the extension just now. Whenever that shows up for you in the app store, can you try that and see if it makes any difference? https://chrome.google.com/webstore/detail/full-page-screen-capture/fdpohaocaechififmbbbbbknoalclacl?authuser=1
