### ISSUE TITLE
Unchecked runtime.lastError

### ISSUE THREAD

**Issue by strongant** [mrcoles/full-page-screen-capture-chrome-extension#56]
Unchecked runtime.lastError while running tabs.captureVisibleTab: Failed to capture tab: unknown error.
![image](https://cloud.githubusercontent.com/assets/7685936/17878163/890660f8-691b-11e6-9b81-7c75d6e0a175.png)

chrome.tabs.captureVisibleTab throws this error,why?

**Comment by mrcoles** [comment]
IDK—sounds like you’re building something using api.js? Try digging into the google chrome extension docs.
