### ISSUE TITLE
Cannot Create Screenshot OS X 10.11.6

### ISSUE THREAD

**Issue by randomdrake** [mrcoles/full-page-screen-capture-chrome-extension#57]
For a little while now, I haven't been able to take screenshots and have had to resort to other tools. They're terribly bloated and not as nice as this one so I figured I'd create an issue to see if a fix could be had.

I've tried both local URLs for development (http://local.something) or remote sites (https://google.com) and they both result in:

> Screen capture in progress, your finished image will open in a new window once completed. Please wait for the progress bar to finish.
> 
> Uh oh, something went wrong! Try reloading the page, verifying javascript is enabled, and running this again. 
> 
> If the problem persists, please report the error in the Chrome webstore. Please include the URL you tried it on and the version of Chrome.

Here's what console spits out:

> page.js:89 fullHeight 4656 fullWidth 1484
> page.js:90 windowWidth 1484 windowHeight 1339
> page.js:91 xDelta 1484 yDelta 1139
> page.js:94 arrangements [0,3317], [0,2178], [0,1039], [0,-100]

I checked to be sure my Chrome is up to date and I appear to be on the latest:

> Version 53.0.2785.89 (64-bit)

Let me know if I can provide any additional details. Thanks!

**Comment by mrcoles** [comment]
Thank you for the informative issue @randomdrake !  Can you please also try right-clicking on the popup and hitting inspect on that to see if you get the error too? Let me know and we’ll take it from there.

I’ve unfortunately been unable to create this issue myself, but a number of people have definitely been reporting it (less thoroughly than you 😏 ).  Additionally, I have not tested it on Chrome 53.x yet… it will be interesting to see if that has anything to do with it.

**Comment by randomdrake** [comment]
@mrcoles I'm not certain what you mean by 

> hitting inspect on that to see if you get there error too

I went ahead and did that and it ran through it's thing, reported the same as above. Nothing in console, just the HTML output:

https://gist.github.com/randomdrake/b4ab457183f47b04a22200e7960cbf8b

Thanks for the prompt response and let me know if there's anything else I can do to help.

**Comment by mrcoles** [comment]
If you right click on the pop up and view the "console" tab in the window
that pops up are there any other logs or errors than what else you've
previously posted?

**Comment by randomdrake** [comment]
Sorry, but no.

Here's what I did.

Attempted to run it and got:
<img width="322" alt="screenshot 2016-08-31 15 06 02" src="https://cloud.githubusercontent.com/assets/1679509/18148096/9f261d84-6f8c-11e6-8cf1-4d1b1376d850.png">

Right clicked and inspected:
<img width="277" alt="screenshot 2016-08-31 15 06 13" src="https://cloud.githubusercontent.com/assets/1679509/18148105/a916e6c0-6f8c-11e6-8fb0-e659c6dd3777.png">

It ran again, and provided:
<img width="319" alt="screenshot 2016-08-31 15 06 34" src="https://cloud.githubusercontent.com/assets/1679509/18148121/b2664ce8-6f8c-11e6-823c-5485365ef18a.png">

And the window looked like:
![screenshot 2016-08-31 15 06 48](https://cloud.githubusercontent.com/assets/1679509/18148126/bb0b582a-6f8c-11e6-905d-dd9688467879.png)

**Comment by randomdrake** [comment]
@mrcoles so I went ahead and started digging into the code. When I installed from the git clone, it worked just fine!

Of note, in the Extensions window it lists it as **Full Page Screen Capture** *1.0.1* - but it works just like it used to. No errors or anything.

**Comment by mrcoles** [comment]
@randomdrake hrm… interesting. I pushed an update to the chrome webstore for v2.2 that does some better logger. Whenever you get the update, if you try right-clicking on the extension popup to inspect again and see if anything comes up in the console, LMK. It should say something now in red, and if you click on the little gray arrow to the left of the error message, it will expand to show a short stack trace.

**Comment by randomdrake** [comment]
@mrcoles well, the new version works like a charm. There's no error to report. Just seeing the nice new header for the first time (nice addition). 

Sorry, I know you were probably hoping for an error to point to but everything seems to work just fine now. Sometimes that's okay too, right?

**Comment by mrcoles** [comment]
Ha! Yeah, a little disappointed, but happy it's at least working. Please
report if you see this again, and thank you for creating the issue! 😎

**Comment by beto-c** [comment]
@randomdrake and @mrcoles FYI, thank you for this thread! Just got this error and it was driving me crazy (because I love this extension). Inspected the pop-up and, lo and behold, found the issue:

> `errorHandler` DOMException: The operation failed because it would cause the application to exceed its storage quota. errorHandler @ popup.js:98

![screen shot 2017-05-03 at 12 26 16 pm](https://cloud.githubusercontent.com/assets/28362822/25678827/f4a3eece-2fff-11e7-85e0-82c689bb61cb.png)

Now trying to figure out where the cache is for this so I can see if deleting items will resolve it.

**Comment by mrcoles** [comment]
hey @beto-c it’s best to create a new issue rather than add to an existing one (unless you’re certain it’s the same underlying issue)

However, for your particular case, if you go to the result of a screenshot and click on the clock icon in the top right, then you can see all the old screenshots. If you scroll all the way to the bottom, you there’s a link to clear all of the screenshots. Maybe that helps?

**Comment by Dreeg** [comment]
Hi, I'm having the same @beto-c  problem and I don't find where to empty the storage.
> [...] if you go to the result of a screenshot and click on the clock icon in the top right, then you can see all the old screenshots.

However, online I found these suggestions:
- https://stackoverflow.com/a/22457496
- https://developer.chrome.com/apps/storage

**Comment by mrcoles** [comment]
@Dreeg scroll to the bottom of that view and click on the link that says “Clear all screen captures”

<img width="433" alt="screen shot 2017-12-31 at 12 18 16 pm" src="https://user-images.githubusercontent.com/136651/34463289-c8014144-ee24-11e7-80e6-46e890425462.png">

**Comment by Dreeg** [comment]
My problem is to find "that view". I can only see site page and pop-up of application, at most the inspection of the two pages.

**Comment by mrcoles** [comment]
@Dreeg Ah, I see. Try this out:

1. Go to Window > Extensions and find the ID for the “Full Page Screen Capture”, e.g.,

        ID: niklbhhahbmbkhkgdlgogdcfebmlfcok

2. Insert that ID value into this URL: `chrome-extension://<id_here>/capture/index.html`

3. Paste that into your browser and you should now be on a screen where you can click the “View Captures” icon on the top right

Let me know if this works or not. I clearly need to come up with a better solution here, but your answer will help.

**Comment by autoforce** [comment]
This message was created automatically by mail delivery software.

A message that you sent could not be delivered to one or more of its
recipients. This is a temporary error. The following address(es) deferred:

  isaianemendonca@gmail.com
    Domain autoforce.com.br has exceeded the max emails per hour (155/150 (103%)) allowed.  Message will be reattempted later

------- This is a copy of the message, including all the headers. ------
Received: from o6.sgmail.github.com ([192.254.113.101]:6423)
	by box907.bluehost.com with esmtps (TLSv1.2:ECDHE-RSA-AES128-GCM-SHA256:128)
	(Exim 4.89)
	(envelope-from <bounces+848413-9636-isaiane=autoforce.com.br@sgmail.github.com>)
	id 1eWPWU-0007Z0-DE
	for isaiane@autoforce.com.br; Tue, 02 Jan 2018 09:34:42 -0700
DKIM-Signature: v=1; a=rsa-sha1; c=relaxed/relaxed; d=github.com; 
	h=from:reply-to:to:cc:in-reply-to:references:subject:mime-version:content-type:content-transfer-encoding:list-id:list-archive:list-post:list-unsubscribe; 
	s=s20150108; bh=gIzo+xjnlLKZ3ENg9zKjI+sIqCk=; b=mv7e4ok4TqNsZbpk
	yFVvovj0X03wUmrER/1JN4fPtU4qT8mv8D+DOdQkk5J6U0GRQYAkHsfN5WaskEDf
	HBo2U31R8P4tj/2dwKcwXbhforyjW6aTFi49AeesoBPuNENZ+LxzwjWn74FyO0gH
	A4DzO3MPUYZzDYnbfRYJ19JtBK0=
Received: by filter0512p1las1.sendgrid.net with SMTP id filter0512p1las1-2688-5A4BB491-15
        2018-01-02 16:34:25.564136935 +0000 UTC
Received: from github-smtp2a-ext-cp1-prd.iad.github.net (github-smtp2a-ext-cp1-prd.iad.github.net [192.30.253.16])
	by ismtpd0015p1iad2.sendgrid.net (SG) with ESMTP id JNWppI_qQhSNiEyQNiUZiA
	for <isaiane@autoforce.com.br>; Tue, 02 Jan 2018 16:34:25.562 +0000 (UTC)
Date: Tue, 02 Jan 2018 16:34:25 +0000 (UTC)

**Comment by mrcoles** [comment]
This was resolved in a recent update—I think v2.4. The manifest needs `unlimitedStorage` as a permission to avoid that quota error. Sorry for the long delay, thank you for the info! 🍕 🍕 🍕
