### ISSUE TITLE
Doesn't work on pages with framesets

### ISSUE THREAD

**Issue by bennigraf** [mrcoles/full-page-screen-capture-chrome-extension#58]
Hi,

the extension doesn't seem to work on pages with framesets (it doesn't scroll at all).

I tried inside a TYPO3 backend.

It would be an option to be able to select a frame to create a screenshot of, if that's possible.

Besides that, it's still a great tool for all webpages that are less than 15 years old ;-).

Best and thanks,
Benni.

**Comment by mrcoles** [comment]
Hi @bennigraf — yeah, framesets are quite tricky and in this modern day and age, a very odd choice for a web page. I’ll let you know if I develop something on this, but it’s definitely not at the top of my priorities. As a workaround, you could open a specific frame in it’s own window, then run it on that—I think you can right-click and select something along the lines of “Open Frame in New Window”? (I’m just guessing what it might say)

**Comment by bennigraf** [comment]
Hi,

thanks for your response. You're right, framesets are a bit out of date ;-). In that special case I tried with opening the frame, but the page also used "overflow:scroll;" to show a fixed header, which also didn't work with the plugin. But I also really wouldn't know how to approach that problem.

Best,
Benni.

**Comment by mrcoles** [comment]
Yeah, since you know what you’re doing, you can adjust the CSS accordingly via developer tools and hit go. Doing that in a more generic way across the whole web is more problematic though.

**Comment by d2s** [comment]
Another option is to create an user style https://userstyles.org/ for the site with Stylish browser extension. Basically, anyone with at least basic CSS skills can create custom CSS stylesheet that will be applied to pages under a certain URLs. User stylesheets work nicely for making more clean visual look for printing page content too (in addition to taking screenshots of).

**Comment by mrcoles** [comment]
I’m closing for now. Sadly, framesets are a low priority compared to other more common issues. Hopefully @d2s idea or the open frame in new window approach can work as a workaround for your particular case. Good luck 😎
