### ISSUE TITLE
JPG instead of PNG

### ISSUE THREAD

**Issue by vyskoczilova** [mrcoles/full-page-screen-capture-chrome-extension#60]
Hi I would like to ask - is possible to set up jpg printscreen instead of png as default? I haven't found any settings. Thanks a lot it's really a great plugin
K.

**Comment by dboune** [comment]
Another opinion: I prefer PNG generally speaking, but would love the option to output JPG.

**Comment by evadknarf** [comment]
you can do a simple: convert -f jpg *.png

**Comment by mrcoles** [comment]
I added this in the Chrome web store version, but not in this repo yet.
