### ISSUE TITLE
Vivalidi browser captures popup?

### ISSUE THREAD

**Issue by mrcoles** [mrcoles/full-page-screen-capture-chrome-extension#62]
via flyingrhino - http://mrcoles.com/full-page-screen-capture-chrome-extension/#comment-3063645445

> Hi, Firstly - LOVE YOUR WORK !!!
> Thank you very much for making our lives so much happier with this wonderful extension.
> 
> Secondly, a small bug - Using Vivaldi browser (win8.1 and Linux mint 17.3 xfce), when I make the capture, it always has the pacman message box at the top right of the final image.
> A possible solution is to capture the first part of the screen BEFORE displaying the pacman , then display it as you scroll. 
> This can be implemented by adding a small delay before displaying the pacman. In order to satisfy users who are not affected by this bug, the delay can be user-configurable in the settings from 0 mSec to ?? mSec .
> 
> Bug appears on every page I try to capture.
> If you need me to upload/email you example screenshots, please feel free to contact me.
> 
> Thanks again !

**Comment by colorfulberry** [comment]
@mrcoles Thanks with you nice screen capture chrome extension. One thing I want to know, how to add the header to chrome extensions? 
![image](https://cloud.githubusercontent.com/assets/8124046/21674216/af871ea0-d367-11e6-97a0-3686a155084b.png)

**Comment by mrcoles** [comment]
@colorfulberry I would include that on a separate issue. Are you asking to represent the browser itself, e.g., the address bar, back button, etc.?

**Comment by mrcoles** [comment]
Closing this issue for now. I have the extra request on my own backlog.
