### ISSUE TITLE
Location of 'capture' directory in project

### ISSUE THREAD

**Issue by tobi-or-not** [mrcoles/full-page-screen-capture-chrome-extension#63]
Hi,

I have been looking at the project to try some modifications. Maybe I am lacking fundamental understanding of Chrome extensions but I am unable to find the directory (and its content) 'capture' in the repository.
In Chromes dev tools, I can see it but do not know how to get there to make changes.

![screen shot 2017-02-02 at 10 09 35](https://cloud.githubusercontent.com/assets/794323/22543307/4b092c96-e930-11e6-8a8a-439a9267da9d.png)

Can someone give me a pointer?

**Comment by ReessKennedy** [comment]
+1 on this. I want to change this from my downloads directory to my cloud drive.

**Comment by mrcoles** [comment]
@tobi-or-not clone the repo and add it as an unpacked extension into chrome. (From the extensions page, click on “Load unpacked extension…”)  Then you can just edit the code wherever you just pointed it at and it will reflect your changes.

@ReessKennedy I think you and tobi are talking about different things. It sounds like you want to know where the images go. It puts them into special file system that Chrome manages directly, which is not exposed to the rest of the filesystem. I will try to update you if I get changes in there to support more.

Cheers!
