### ISSUE TITLE
iFrames and CORS

### ISSUE THREAD

**Issue by mshaked1** [mrcoles/full-page-screen-capture-chrome-extension#64]
Two questions:
1. Do you know if this extension has any issues with CORS in terms of using canvas.toDataUrl on tainted vs non-tainted images?
2. Do you think it's at all possible to capture iframe content? Most of what I read makes it seem impossible.

**Comment by mrcoles** [comment]
Hi @mshaked1 — sorry for the late reply, but I believe the extension’s extra privileges avoid these issues. It uses the [chrome.tabs.captureVisibleTab method](https://developer.chrome.com/extensions/tabs#method-captureVisibleTab) to take the screenshots at each position on the page.
