### ISSUE TITLE
Cannot capture on http://ozarkchamber.com/Missouri/

### ISSUE THREAD

**Issue by xtoq** [mrcoles/full-page-screen-capture-chrome-extension#65]
Chrome version 59.0.3071.86

**Comment by mrcoles** [comment]
The latest updates likely resolved the error you’re getting. Please try again with v2.6 or later.

Thanks!

![screencapture-ozarkchamber-missouri-1517870819793](https://user-images.githubusercontent.com/136651/35832841-bc20286a-0a9c-11e8-9455-7867bb837099.png)
