### ISSUE TITLE
Split Image

### ISSUE THREAD

**Issue by apusing** [mrcoles/full-page-screen-capture-chrome-extension#66]
I am using this extension for a project. It works quite well.
While going through the code a saw a function "splitNotifier". I realise that this will happen when there are more than one screenshots. But I haven't been able to figure out the scenario where this will happen. Please explain this.

**Comment by DerangedMind** [comment]
@apusing This would occur if the page you are trying to take a screenshot of is too long. It would then split the screenshots to ensure that the single screenshot isn't too big.
