### ISSUE TITLE
Horizontal lines due to different DPI scaling of windows

### ISSUE THREAD

**Issue by spacemudd** [mrcoles/full-page-screen-capture-chrome-extension#67]
This is my favorite extension and really, great work!

Lately I've been encountering horizontal lines where the screenshots are being merged.

The page over http://mrcoles.com/full-page-screen-capture-chrome-extension/ shows multiple people having the issue and no solution. (ctrl+f 'black')

I took it upon me to investigate and turns out it's due to Windows' moniter scaling being other than 100%. 

E.g. 
- Moniter scaling 100% 
![100-dpi-scale](https://user-images.githubusercontent.com/20286281/27762441-04fc3ec6-5e7b-11e7-8bbc-21af98d13fb9.png)

- Moniter scaling 125%
![125-dpi-scale](https://user-images.githubusercontent.com/20286281/27762446-1086c734-5e7b-11e7-8071-8346899e1702.png)

- Moniter scaling 150%
![150-dpi-scale](https://user-images.githubusercontent.com/20286281/27762451-222d9666-5e7b-11e7-87f7-3ebbc521be90.png)

**Comment by evadknarf** [comment]
I have both horizontal / vertical lines... generally they are the scroll bars when the screenshots becomes too big or the ratio is too close to the current window size????

Failed at 30000 X 20000 screenshot. javascript stopped working.

**Comment by mrcoles** [comment]
Hey @spacemudd I’m looking into various issues currently. Are you still seeing this issue with your latest version of Windows and Chrome? I don’t have a Windows rig to test this out, but from examining your screenshots (awesome reporting, btw!) I it looks like both the bottom and right side of each capture are getting 1 extra pixel of a black line.

**Comment by spacemudd** [comment]
@mrcoles I'm not seeing it anymore! Now that I'm back to this thread, I believe this isn't an issue with the extension itself but it's an issue with Chrome. As I have noticed some several other extensions (e.g. LastPass, Vue Dev Tools) sometimes don't work well with different dual-monitors running different DPI resolutions

I'm closing my issue.

Thank you.

**Comment by mrcoles** [comment]
Awesome, thanks!
