### ISSUE TITLE
 Corrupted bottom-left part of the page

### ISSUE THREAD

**Issue by astlin** [mrcoles/full-page-screen-capture-chrome-extension#68]
Hi, I'm using this extension to rasterize svg  images. And I found out that on some svg files, especialy on big ones, the bottom-left part of the raster image is corrupted. Seems as some part of the image is moved down.
![screencapture-file-home-astlin-d0-97-d0-b0-d0-b3-d1-80-d1-83-d0-b7-d0-ba-d0-b8-d0-a7-d1-91-d1-80-d0-bd-d0-be-d0-b1-d0-b5-d0-bb-d1-8b-d0-b9_1234075_35-313793445198x53-46336963833_300dpi_2017-10-26_23-05-16-svg-1509041916957](https://user-images.githubusercontent.com/2429017/32070000-518ce21a-baa4-11e7-90b7-11e2691cd7ae.png)

Original svg is here: https://goo.gl/oGN5bG

**Comment by mrcoles** [comment]
Hi, please try with the latest version of the extension. I’m not sure if something updated or if maybe you needed to wait for the svg to fully load before capturing?

Also, the resulting image was 25MB, so I used [ImageOptim](https://imageoptim.com/mac) to compress it down to 8MB so I could post it here!

![screencapture-astlin-original-svg-1517871409085](https://user-images.githubusercontent.com/136651/35833742-6ec20490-0aa0-11e8-9738-c3313c67f2ca.png)
