### ISSUE TITLE
Unable to capture screens after upgrading to  Chrome V 62.0.3202.09

### ISSUE THREAD

**Issue by aflores** [mrcoles/full-page-screen-capture-chrome-extension#70]
Hello MrColes!

Looks like your most excellent Full Page Screen Capture Ver 2.2 is not compatible with Chrome V 62.0.3202.09 (Official Build) (64-bit) on Windows 7.

When I click on the camera icon I get:

Screen capture in progress, your finished image will open in a new window once completed. Please wait for the progress bar to finish.

Uh oh, something went wrong! Try reloading the page, verifying javascript is enabled, and running this again. 

If the problem persists, please report the error in the Chrome webstore. Please include the URL you tried it on and the version of Chrome.

**Comment by mrcoles** [comment]
Hey @aflores 

Can you share:

1. The URL you’re trying

2. Can you right-click on the popup window that has that error message, click on “inspect”, click on the “console” in the resulting popup window and copy-paste any text from that?

**Comment by mrcoles** [comment]
I’m closing this ticket due to inactivity. There is now a report feature in the extension (if there’s an error or via the flag icon on the resulting capture page). Please report future issues there.
