### ISSUE TITLE
Feature Request: No Background image option please...

### ISSUE THREAD

**Issue by everything-it** [mrcoles/full-page-screen-capture-chrome-extension#71]
I thought this was the app that already did it, but I guess not, or I can't find out how. Problem: When you have a webpage with a gradient background that does NOT scroll with the page, when you take a full page screenshot in "sections" ...you end up with a repeating background that goes from dark to light, to dark, to light, to dark, to light...over and over again, and it looks crappy. Most sites with this type of background have a general single color underneath the background image as a fall-back, and that is the desireable way to capture the full page on this type of thing...I had something that did it once, but can't find what I did them with. 
![worship101-org-greg-laurie-a-new-beginning](https://user-images.githubusercontent.com/31141542/33226521-a33613d2-d144-11e7-98e8-d4b2fe9e19f7.png)
![nobg-worship101-greglaurie](https://user-images.githubusercontent.com/31141542/33226522-ae96b768-d144-11e7-9299-b63f8504abc4.png)  (ref: https://worship101.org  for one example)

**Comment by mrcoles** [comment]
Hey @everything-it — I think this particular issue is out of the scope of the extension. I’ll keep it in mind for future advanced features, but some advanced functionality around scrolling and other issues like that are currently the priority. I would recommend in this kind of scenario—if you’re comfortable with HTML/CSS—to just edit the page manually in Inspector before capturing it.
