### ISSUE TITLE
Could not load extension icon `images/icon16-999.png`

### ISSUE THREAD

**Issue by brentchow** [mrcoles/full-page-screen-capture-chrome-extension#74]
![image](https://user-images.githubusercontent.com/3849502/35822894-b7d737b0-0a7b-11e8-9812-c8e657512c9b.png)

![image](https://user-images.githubusercontent.com/3849502/35822979-078a42f2-0a7c-11e8-86ef-2deff6b44783.png)

v2.5 in the [Chrome Store](https://chrome.google.com/webstore/detail/full-page-screen-capture/fdpohaocaechififmbbbbbknoalclacl?hl=en-US) is missing the extension icon. As a result, users cannot add the extension.

**Comment by mrcoles** [comment]
Hey Brent, thank you so much for reporting this. I updated the extension to v2.6 and it’s sorted now. Enjoy! 🏄
