### ISSUE TITLE
Nice to have: Ability to print the screenshot

### ISSUE THREAD

**Issue by StealthyDev** [mrcoles/full-page-screen-capture-chrome-extension#75]
Printing the captured screenshot takes a lot of effort, as its saved as an image. If you send the image to printer, it prints stupid.

Adding ability to save as PDF will eliminate this problem, may be?

Cheers.

**Comment by mrcoles** [comment]
Hi, the [webstore version](https://chrome.google.com/webstore/detail/full-page-screen-capture/fdpohaocaechififmbbbbbknoalclacl?hl=en-US) now has this feature. Cheers!
