### ISSUE TITLE
Lines appearing when needing to scroll

### ISSUE THREAD

**Issue by jthanto** [mrcoles/full-page-screen-capture-chrome-extension#78]
Hi, first of all - thanks, nice tool.  But I am experiencing some weird stuff. 
At work some of my colleagues are using this tool for capturing whole sites, but one is having problems regarding lines appearing where scrolling happen (ref. image). 

![capture](https://user-images.githubusercontent.com/5312099/40044349-623c5ade-5827-11e8-8541-f1458865102b.png)

I myself have not been able to make the exact same problem appear, and we have tried updating chrome and the extension. We are using a wide range of chromebooks, and everything have been working fine until lately. Have anyone experienced something like this? What could be the source?

**Comment by mrcoles** [comment]
Hey @jthanto, if you’re using the [webstore version](https://chrome.google.com/webstore/detail/full-page-screen-capture/fdpohaocaechififmbbbbbknoalclacl?hl=en-US), can you report this via the reporting tool (flag icon) within the extension? That is set up to review specific cases like this. It appears the page you’re capturing is doing something non-standard with its scrollbars and they are showing up in the image.
