### ISSUE TITLE
prevent unwanted scrolling

### ISSUE THREAD

**Issue by asmod3us** [mrcoles/full-page-screen-capture-chrome-extension#79]
I remember using an option to prevent unwanted scrolling with this extension, but I can no longer find it in the options. Is there any other way to prevent full page screen capture to scroll if it gets confused on a page?

**Comment by mrcoles** [comment]
The features were:

*   fixed elements - enable/disable - overrides to fixed position elements to try and stop them from repeating on every capture
*   advanced scrolling - enable disable - this determined whether or not it looked for sub-elements on the page to scroll when the page appeared to not scroll

They are not available as options anymore, but if you report them via the reporting tool in the extension, I’d be happy to take a look and it’ll be easier to debug. There are a number of improvements in the current dev build that will go live this week. Also, those updates live in a private fork.
