### ISSUE TITLE
Doesn't honor download directory

### ISSUE THREAD

**Issue by ChaosCom** [mrcoles/full-page-screen-capture-chrome-extension#82]
Hello,

the option page for the extension states underneath Download / Directory: "Specify a directory underneath your downloads directory to save your screenshots [..]"

However this seems to be not the case. The captured screenshots do not end up in my Chrome's Download folder, nor in any subdirectory of it. 

So my question is: 
1. Where are the files that show up under "History" stored in?
2. Why doesn't the extension honor Chrome's Download folder setting?

**Comment by mrcoles** [comment]
Hey, can you share:

*   OS and version
*   Chrome version (you can get this from chrome://settings/help)
*   Extension version (you can get this from chrome://extensions/?id=fdpohaocaechififmbbbbbknoalclacl)

> 1. Where are the files that show up under "History" stored in?

They’re stored within Chrome using the HTML5 file system. They’re sandboxed and available only to the extension and they are only on your computer.

> 2. Why doesn't the extension honor Chrome's Download folder setting?

This must be a bug. I have had a few other reports about it. I am yet to be able to reproduce it. Are you able to get any different results by trying different folder names or changing other settings? Anything that might help sort this out would be a huge help.

**Comment by mrcoles** [comment]
Please re-open if there’s more info…
