### ISSUE TITLE
Making it concurrent

### ISSUE THREAD

**Issue by The-Gupta** [mrcoles/full-page-screen-capture-chrome-extension#84]
I want to use this library for automation where multiple screenshots be asynchronously (independently in parallel) captured? Currently, it does not work if I click for another screenshot before previous one has finished.

**Comment by mrcoles** [comment]
The extension runs via code in the popup. If you navigate away from the page then the popup will close and the screenshot will not complete. I would recommend using a different tool to capture the pages for automation. Maybe something like this: http://www.paulhammond.org/webkit2png/ or I’m sure there are other solutions out there.
