### ISSUE TITLE
Making it 100X faster

### ISSUE THREAD

**Issue by The-Gupta** [mrcoles/full-page-screen-capture-chrome-extension#85]
Could you suggest how it can be made much faster?

**Comment by mrcoles** [comment]
You could change `CAPTURE_DELAY` to 0: https://github.com/mrcoles/full-page-screen-capture-chrome-extension/blob/master/page.js#L2

The delay exists because a number of things happen during scroll that if captured immediately might end up with unintended results in the final capture.
