### ISSUE TITLE
github version != chrome web store version

### ISSUE THREAD

**Issue by Pilen** [mrcoles/full-page-screen-capture-chrome-extension#86]
Why are the the two versions differing?
I find it unfortunate as I prefer open source solutions.
At the same time it is slightly deceiving as it looks like it is open source, you have to be careful to notice the huge version gap, or the minor note in the readme.

What were the reasons for doing this split?
Are there any plans to bring actual development back to this repo?

**Comment by mrcoles** [comment]
Hi @Pilen 

Valid concern! I’ve been working on a bunch of updates and I’m looking to add some additional premium features (keeping the existing functionality free). While I’ve been doing this, I decided to fork the repo and work on a private branch. I’m working full-time on it and currently not making any money. Once I have this all working, I can review the open-sourcing strategy again.

I updated the README 9 months ago to reflect the difference between the two: https://github.com/mrcoles/full-page-screen-capture-chrome-extension/commit/350d415f76f435f48e5c5e5174927cc0d71e79c3

I updated the text in the Webstore at the same time:

> This extension is run by an independent developer. View the original open source project on github: https://github.com/mrcoles/full-page-screen-capture-chrome-extension

It also makes sense to me to leave this repo available regardless.

Hopefully, with the extension able to earn some revenue I can pay someone to provide customer support. So far I have been doing that myself, and it has led to a ton of improvements in both updates to how it captures pages (e.g., fixed position elements, iframes, and all sorts of weird edge cases) and also in identifying when Chrome has introduced breaking changes. Also, I can use the money to pay for i18n translations 😄
