### ISSUE TITLE
Versions in Github and Chrome web store don't match.

### ISSUE THREAD

**Issue by diego-rey** [mrcoles/full-page-screen-capture-chrome-extension#89]
I have cloned the repository in Github but when loading this extension I have seen that the version is 1.0.1, while downloading it from [webstore](https://chrome.google.com/webstore/detail/full-page-screen-capture/fdpohaocaechififmbbbbbknoalclacl), the version is 5.1.

The repository in Github doesn't have the capture.html file and the logic of how to join all the captures in one. I am interested in knowing how you solved this for a personal project. Is there any way to update the repository or know how you did this? Thank you.

**Comment by benji6** [comment]
I've just noticed this too, was really confused before I realised there's a big divergence between the code here and the code in the Chrome Store. Would be great to have a notice in the readme about this

**Comment by mrcoles** [comment]
I’ve been doing work on a private branch, which I currently plan to keep private. From the [README](https://github.com/mrcoles/full-page-screen-capture-chrome-extension/blob/350d415f76f435f48e5c5e5174927cc0d71e79c3/README.md):

> NOTE: the webstore version is now running on a private branch of this repo and will have more updates.

Regarding the specific question about joining captures—are you referring to combining them into one PDF? I have been using the [jsPDF](https://github.com/MrRio/jsPDF) library to assemble PDFs.

**Comment by benji6** [comment]
Ah sorry, I missed that note, should have read the whole thing. Thanks for leaving this code here anyway, it's been helpful to get a rough idea about how the extension works

**Comment by diego-rey** [comment]
No, my question arises because if you use the extension from the repository in Github, the screenshots taken from the site are assembled badly and the image of the entire site looks bad. This does not happen in the version that is in the webstore.

**Comment by mrcoles** [comment]
@diego-rey yeah, there are a number of improvements in the web store version that take extra steps to handle tricky pages (the web is a wacky place!) I’m currently keeping that branch private, if it changes, I’ll try to update this issue.
