### ISSUE TITLE
no longer scrolls full page #2

### ISSUE THREAD

**Issue by zesschrno** [mrcoles/full-page-screen-capture-chrome-extension#91]
Computer, ASUS TUF Gaming FX504 with Win 10

Browser: Vivaldi
Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/74.0.3729.172 Safari/537.36 Vivaldi/2.5.1525.48

I don't know, inner scroll on modal bootstrap stop scrolling for taking full picture, i use this extension in my daily work but recently stops working.

on body section of modal bootstrap i have:

`<div class="height-80vh" style="overflow-y:auto;">  inner long text </div>`

**Comment by mrcoles** [comment]
Hey @zesschrno if the extension doesn’t scroll a particular page it’s generally specific to that page and it tends to be a new issue with a type of page that was never supported as opposed to a regression.

Can you report this using the "report issue" tool (flag icon) in the extension? I’m currently a little behind on those tickets, but mention this github issue and I’ll see if I can find it.
