### ISSUE TITLE
Can't remove keyboard shortcut from this extension

### ISSUE THREAD

**Issue by garyking** [mrcoles/full-page-screen-capture-chrome-extension#94]
For this extension specifically, I can't remove the keyboard shortcut. When I press the `x` to remove the shortcut, and then reload the page, the shortcut is re-added.

This doesn't happen with other Chrome extensions.

**Comment by mrcoles** [comment]
@garyking this seems like something to do with how Chrome works, not the extension itself. The extension is using the [chrome.commands API](https://developer.chrome.com/apps/commands) with the following defined in the manifest.json file: https://github.com/mrcoles/full-page-screen-capture-chrome-extension/blob/master/manifest.json#L10
