### ISSUE TITLE
Using author's extension in mine

### ISSUE THREAD

**Issue by Aroxed** [mrcoles/full-page-screen-capture-chrome-extension#96]
Hi.
Nice extension!
I'm also developing a Chrome Extension and I need to take screenshots too. 
Is there a way to integrate your extension (or its part) in my code?
And is there a way to take screenshot of particular selector, like document.getElementById('p1') ?

Thanks.

**Comment by mrcoles** [comment]
Take a look at the captureVisibleTab API
https://developer.chrome.com/extensions/tabs#method-captureVisibleTab

To get a specific element, you’ll have to identify its coordinates on the
page and extract that from the screenshot of the visible tab, e.g.,
position and draw it onto a smaller canvas object.
