### ISSUE TITLE
Capturing this page results in a tall blank page 

### ISSUE THREAD

**Issue by garyking** [mrcoles/full-page-screen-capture-chrome-extension#97]
**Describe the bug**

When I try to capture [this iPhone comparison URL on Apple.com](https://www.apple.com/iphone/compare/), it results in a tall, blank page.

**To Reproduce**

1. Go to URL: https://www.apple.com/iphone/compare/
2. Capture the page.
3. In the preview, it's a tall blank page.

**Expected behavior**

It should result in a screenshot of the page.

**Screenshots**

[Tall blank page screenshot](https://user-images.githubusercontent.com/343940/64808044-79e4e280-d564-11e9-8a73-6d561d1f286d.png)

**System (please complete the following information):**

 - OS: MacOS 10.14.6 (18G95)
 - Browser and version: Chrome 77.0.3865.75
 - Extension version: 5.5

**Additional context**

(none)

**Comment by mrcoles** [comment]
Hi @garyking thanks for reporting this and going the extra mile to put together a nice bug report 😎 

I’m seeing you’re on a pretty recent Chrome update (77.0.3865 released on 2019-09-10). I’ve seen some inexplicable behavior by Chrome after browser upgrades. Can you carefully test the following steps in order and let me know what you find out?

1. Try screenshotting https://www.example.com/ - does that work?
2. Try restarting your computer and screenshot again - does that work?
3. …let’s wait for those and dig deeper if it’s still no good

**Comment by garyking** [comment]
Restarting the browser fixed the issue, thanks.

**Comment by mrcoles** [comment]
Was it just restarting the browser or the whole OS?

**Comment by garyking** [comment]
Just the browser.

**Comment by mrcoles** [comment]
@garyking actually one more thing—there might be something about page size—can you also test this page: https://mrcoles.com/media/fpsc/blank-image.html

**Comment by garyking** [comment]
I tested 3 pages, in this order, and immediately one after the other: your test page, the iPhone compare URL, and the Example site. I've attached the screenshots. Your test page is the only one that's blank. 

[Test page](https://user-images.githubusercontent.com/343940/64885278-b0d4fa00-d631-11e9-86cf-74aefd9dad20.png)
[iPhone compare](https://user-images.githubusercontent.com/343940/64885243-96028580-d631-11e9-9867-34848d81e298.png)
[Example](https://user-images.githubusercontent.com/343940/64885241-96028580-d631-11e9-998b-7ce59f1d8a93.png)

**Comment by mrcoles** [comment]
I did a bunch of debugging today and came up with something that improves stuff drastically and resolves most scenarios where people were seeing this issue, but it’s not 100% there yet for extraordinarily long pages (especially with retina).

I filed a ticket with the Chrome team https://bugs.chromium.org/p/chromium/issues/detail?id=1004026&can=2&q=canvas%20blank

**Comment by mrcoles** [comment]
Some other updates:

1. I reported a number of issues and they put improvements in Chrome 78 to fix a number of them
2. There’s a separate problem with pages being partially zoomed—either via zooming the page in Chrome itself to something other than 100% or if the entire OS is set to zoom things to something other than 1:1 (this 2nd part might be specific to Windows?)
